name: health check

on:
  push:
    branches:
      - main

#on:
#  schedule:
#    - cron: "0 6 * * *"
#  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check if deployed app is healthy
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-yucs.onrender.com/
